config/routes.rb
FakePages::Application.routes.draw do
  resources :sources, :tickers, :pages

  match "/ig/api"      => "pages#random_google"
  match "/quote/:name" => "pages#random_bloomberg"
  match "/q"           => "pages#random_yahoo"
  match "/update"      => "tickers#update_all", :as => :update

  root :to => 'sources#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :ticker
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :tickers
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
  belongs_to :source
  has_many :pages

  def name_with_source
    "#{name} (#{source.name})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  def random_bloomberg
    @page = Source.find_by_name("bloomberg").tickers.find_by_name(params[:name]).pages.sample
    render "show"
  end

  def random_google
    @page = Source.find_by_name("google").tickers.find_by_name(params[:stock]).pages.sample
    render "show"
  end

  def random_yahoo
    @page = Source.find_by_name("yahoo").tickers.find_by_name(params[:s]).pages.sample
    render "show"
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false } # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
    @source = Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/1
  # GET /sources/1.json
  def random
    @source = Source.find(params[:id])
    @page = @source.pages.sample

    respond_to do |format|
      format.html # random.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.json
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render json: @source, status: :created, location: @source }
      else
        format.html { render action: "new" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.json
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  # GET /tickers
  # GET /tickers.json
  def index
    @tickers = Ticker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickers }
    end
  end

  # GET /tickers/1
  # GET /tickers/1.json
  def show
    @ticker = Ticker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticker }
    end
  end

  # GET /tickers/new
  # GET /tickers/new.json
  def new
    @ticker = Ticker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticker }
    end
  end

  # GET /tickers/1/edit
  def edit
    @ticker = Ticker.find(params[:id])
  end

  # POST /tickers
  # POST /tickers.json
  def create
    @ticker = Ticker.new(params[:ticker])

    respond_to do |format|
      if @ticker.save
        format.html { redirect_to @ticker, notice: 'Ticker was successfully created.' }
        format.json { render json: @ticker, status: :created, location: @ticker }
      else
        format.html { render action: "new" }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickers/1
  # PUT /tickers/1.json
  def update
    @ticker = Ticker.find(params[:id])

    respond_to do |format|
      if @ticker.update_attributes(params[:ticker])
        format.html { redirect_to @ticker, notice: 'Ticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_all
    require "net/http"
    require "uri"

    Ticker.all.each do |ticker|
      uri = URI.parse(ticker.source.url + ticker.name)
      res = Net::HTTP.get_response(uri)
      page = Page.new :ticker => ticker, :content => res.body
      page.save
    end

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  # DELETE /tickers/1
  # DELETE /tickers/1.json
  def destroy
    @ticker = Ticker.find(params[:id])
    @ticker.destroy

    respond_to do |format|
      format.html { redirect_to tickers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FakePages</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li><%= link_to_unless_current "Sources", sources_path %></li>
      <li><%= link_to_unless_current "Tickers", tickers_path %></li>
      <li><%= link_to_unless_current "Pages", pages_path %></li>
    </ul>
  </nav>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %><br />
    <%= f.collection_select(:ticker_id, Ticker.all, :id, :name_with_source) %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Source</th>
    <th>Ticker</th>
    <th>Date</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.ticker.source.name %></td>
    <td><%= page.ticker.name %></td>
    <td><%= page.created_at.localtime.strftime("%B %-d, %Y") %></td>
    <td><%= page.created_at.localtime.strftime("%-l:%M %P JST") %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Update all', update_path %> |
<%= link_to 'New page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<%= raw @page.content %>

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<h1>Listing sources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sources.each do |source| %>
  <tr>
    <td><%= source.name %></td>
    <td><%= source.url %></td>
    <td><%= link_to 'Show', source %></td>
    <td><%= link_to 'Edit', edit_source_path(source) %></td>
    <td><%= link_to 'Destroy', source, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New source', new_source_path %>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>

app/views/tickers/_form.html.erb
<%= form_for(@ticker) do |f| %>
  <% if @ticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticker.errors.count, "error") %> prohibited this ticker from being saved:</h2>

      <ul>
      <% @ticker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.collection_select(:source_id, Source.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickers/edit.html.erb
<h1>Editing ticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticker %> |
<%= link_to 'Back', tickers_path %>

app/views/tickers/index.html.erb
<h1>Listing tickers</h1>

<table>
  <tr>
    <th>Source</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickers.each do |ticker| %>
  <tr>
    <td><%= ticker.source.name %></td>
    <td><%= ticker.name %></td>
    <td><%= link_to 'Show', ticker %></td>
    <td><%= link_to 'Edit', edit_ticker_path(ticker) %></td>
    <td><%= link_to 'Destroy', ticker, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New ticker', new_ticker_path %>

app/views/tickers/new.html.erb
<h1>New ticker</h1>

<%= render 'form' %>

<%= link_to 'Back', tickers_path %>

app/views/tickers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_ticker_path(@ticker) %> |
<%= link_to 'Back', tickers_path %>